### ISSUE TITLE
给你个建议

### ISSUE THREAD

**Issue by Hongyu91** [tamaki-3hs25rk/works#60]
你在我空间污言秽语漫骂法轮功，对我进行人身攻击。我告诉你，你的所作所为是错的，我给你送了些真相资料过来，希望你认真看看，了解什么是法轮功？中共为什么迫害法轮功？为何三退和善待法轮功会保平安？如需详细了解就到我空间来浏览阅读，请注意文明礼貌，不要漫骂法轮功，否则你会遭到天惩的。

[了解更多](https://github.com/Hongyu91/cecjy)

**Comment by tamaki-3hs25rk** [comment]
> [@Hongyu91:](https://github.com/Hongyu91)
> 你在我空间污言秽语漫骂法轮功，对我进行人身攻击。我告诉你，你的所作所为是错的，我给你送了些真相资料过来，希望你认真看看，了解什么是法轮功？中共为什么迫害法轮功？为何三退和善待法轮功会保平安？如需详细了解就到我空间来浏览阅读，请注意文明礼貌，不要漫骂法轮功，否则你会遭到天惩的。
> 
> [了解更多](https://github.com/Hongyu91/cecjy)

@tamaki-3hs25rk:
你好，本人并没有在你的github页面发布关于人身攻击的言论，而且该讨论区是本人转载文章的专区，且转载文章的内容不代表本人的立场，本人仅利用这些文章来学习代码，请你了解详情，谢谢。
